// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Numerologia.Infrastructure.Data;

#nullable disable

namespace Numerologia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428023512_AddAssinaturaTeste")]
    partial class AddAssinaturaTeste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Numerologia.Core.Entities.AssinaturaTeste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArcanoMomento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Escolhida")
                        .HasColumnType("boolean");

                    b.Property<int>("MapaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MapaId");

                    b.ToTable("AssinaturasTeste");
                });

            modelBuilder.Entity("Numerologia.Core.Entities.Consulente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Consulentes");
                });

            modelBuilder.Entity("Numerologia.Core.Entities.MapaNumerologico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoNascimentoReduzido")
                        .HasColumnType("integer");

                    b.Property<int>("CicloVida1")
                        .HasColumnType("integer");

                    b.Property<int>("CicloVida2")
                        .HasColumnType("integer");

                    b.Property<int>("CicloVida3")
                        .HasColumnType("integer");

                    b.Property<int>("ConsulenteId")
                        .HasColumnType("integer");

                    b.Property<string>("CoresFavoraveis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int>("Desafio1")
                        .HasColumnType("integer");

                    b.Property<int>("Desafio2")
                        .HasColumnType("integer");

                    b.Property<int>("DesafioPrincipal")
                        .HasColumnType("integer");

                    b.Property<int>("DiaNascimentoReduzido")
                        .HasColumnType("integer");

                    b.Property<string>("DiasMesFavoraveis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DividasCarmicas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FiguraA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FimCiclo1Idade")
                        .HasColumnType("integer");

                    b.Property<int>("FimCiclo2Idade")
                        .HasColumnType("integer");

                    b.Property<string>("GradeLetras")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HarmoniaAtrai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HarmoniaEOpostoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HarmoniaEPassivoEm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HarmoniaProfundamenteOpostoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HarmoniaVibraCom")
                        .HasColumnType("integer");

                    b.Property<string>("LicoesCarmicas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MesNascimentoReduzido")
                        .HasColumnType("integer");

                    b.Property<int>("Missao")
                        .HasColumnType("integer");

                    b.Property<int>("MomentoDecisivo1")
                        .HasColumnType("integer");

                    b.Property<int>("MomentoDecisivo2")
                        .HasColumnType("integer");

                    b.Property<int>("MomentoDecisivo3")
                        .HasColumnType("integer");

                    b.Property<int>("MomentoDecisivo4")
                        .HasColumnType("integer");

                    b.Property<string>("NomeUtilizado")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("NumeroDestino")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroExpressao")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroImpressao")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroMotivacao")
                        .HasColumnType("integer");

                    b.Property<string>("NumerosHarmonicos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RelacaoIntervalores")
                        .HasColumnType("integer");

                    b.Property<int>("RespostaSubconsciente")
                        .HasColumnType("integer");

                    b.Property<string>("TendenciasOcultas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsulenteId");

                    b.ToTable("Mapas");
                });

            modelBuilder.Entity("Numerologia.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NomeExibicao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Numerologia.Core.Entities.AssinaturaTeste", b =>
                {
                    b.HasOne("Numerologia.Core.Entities.MapaNumerologico", null)
                        .WithMany()
                        .HasForeignKey("MapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Numerologia.Core.Entities.Consulente", b =>
                {
                    b.HasOne("Numerologia.Core.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Numerologia.Core.Entities.MapaNumerologico", b =>
                {
                    b.HasOne("Numerologia.Core.Entities.Consulente", null)
                        .WithMany()
                        .HasForeignKey("ConsulenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
